### ISSUE TITLE
关于llvm插桩代码的几个问题

### ISSUE THREAD

**Issue by zhanggenex** [ICSE2020-MemLock/MemLock#2]
**您好，十分感谢能将这个工作开源！我想跟进一下这个工作，但是代码有几个问题想请教一下。**

- 一、trace_function_stack.c这个文件是在什么时候运行的？它在AFL原本的llvm文件夹里面没有，所以我不是特别清楚这个文件的运行时间以及和其他几个文件的关系；
- 二、afl-llvm-pass-stack.so.cc这个文件里面的有一些代码我不是特别清楚它的作用，以及这个代码的逻辑我也没有看懂。希望你能解答一下
   - （1）第163行`bool functionFlag = true`的functionFlag这个变量的作用是什么？注释里面写的是
        > //第一次进函数时flag为true，插桩后改为false
        
        我不是特别理解第一次进函数和之后进入函数有什么区别，以及为什么要这么做；
   - （2）因为这个代码是基于PerfFuzz的，所以插桩里面还有修改PerfBranchCounter、PerfTotalCounter的代码，这些变量还有用吗？
   - （3）第247行`if(inst->getOpcode() == Instruction::Ret)`判断指令是否是return指令之后，对Counter、PerfBranchCounter、PerfTotalCounter都进行了减1的操作，这个操作的目的是什么？

**十分感谢！**

**Comment by wcventure** [comment]
您好，

一、trace_function_stack.c并不是在特定的时刻运行，它只是定义了一些插桩用的函数。
二、
（1）这个文件应该是用于记录调用栈的深度的，只需要在每个函数头插桩，以及在return指令前插桩即可。这个`bool functionFlag = true`的目的是为了判断该`basicblock`是不是函数的第一个`basicblock`，只在第一basicblock进行插桩。实现方式有很多种，这只是其中一种方式，效率不高，还请见谅。
（2）里面有些变量是perffuzz定义的，有几个用到了，有几个没用到，可能还得仔细研究下代码才知道。
（3）第247行if(inst->getOpcode() == Instruction::Ret)判断指令是否是return指令之后，对Counter、PerfBranchCounter、PerfTotalCounter都进行了减1的操作，Counter和PerfBranchCounter应该有一个是记录当前函数的递归调用深度，PerfTotalCounter记录的是整个call stack的深度。每次有函数被调用，call stack深度加1，有函数返回时，call stack深度减1。利用这几个Counter作为引导，相当于引导程序的栈内存使用不断变大。

感谢您对这个工作的关注！

成
